language: android

android:
  components:
    - tools
    - platform-tools-26.1.1
    - build-tools-28.0.3
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

branches:
  only:
    - master
    - forecast

before_install:
  - yes | sdkmanager "build-tools;28.0.3"
  - yes | sdkmanager "platforms;android-28"

jobs:
  include:
    - stage: check
      name: "lint"
      script: ./gradlew clean lint
    -
      name: "ktlint"
      script: ./gradlew clean ktlint