language: android

android:
  components:
    - tools
    - platform-tools-26.1.1
    - build-tools-28.0.3
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

branches:
  only:
    - master

before_install:
  - yes | sdkmanager "build-tools;28.0.3"
  - yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew clean ktlint