language: android

env:
  global:
    - ANDROID_API=28
    - EMULATOR_API=21
    - ANDROID_BUILD_TOOLS=24.0.2
    - ADB_INSTALL_TIMEOUT=5

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - android-sdk-license-.+

branches:
  only:
    - master

script:
  - ./gradlew ktlint