language: android
android:
  components:
  - tools
  - platform-tools-26.1.1
  - build-tools-28.0.3
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
env:
  global:
    secure: sDvVO57H+Io3jsRM7xeZ1GMDPxm9kgW4RnuTLALyRjt9y+WjvL7n31RodtJdfygpXREyWqYscPLW9bX13LCIWhVggjCYj1v+fr9E7foMrbKM/VdOry5Qo+x13fr13uI4vkXjBQ97ZQ2z3WM1h9o8mwTCdr1s9rklxxurgWJA6T9gaJjX2hn0A6NqKHfnbQIik2k+CSaxv00j9JVmzpau5DYm0BaUcKGMRnWck/GkEBG6EO8HiPzZHTIgvYrdYkLgydIKXsqBNEeyE4n6s1Ym3ZvuoZbyGYa5DXdEdiZuaMjNFAlLo4p/gsmnmS8Lzpbgxie9SZXd97ZYpwk+jhT31SSWcemEBr+PjDH6a21rWmpY4QtA6DG/XIUau70P1sCKq49ib65RL922rsdU9KKQ61pG6uVG+/hjvdFFsuByguTllJniOh0McDPk/O4F5m4thADnlA5fbNMQrL+YT4+550ORoIEQ5T56ZlpaUdmGFN7wHRwMHodQsv1p/pYQwRWCOXvIZQCy2BD1U0aF4zjRVJq7JRsi8xTgb5yHASiCpqOhRpKp7l5NLeovzK2l4JpEOq53lnT8Q3d1W71Re0pTqSwvmiE3iaTSHILTFtkeKEwexF72OtGF6ZhkvAUIb4NKKDQQfqs20/E1bXbbYG4VznUaZAPfWGVR2SSTVXELQ0A=
branches:
  only:
  - master
  - googlemap
before_install:
- yes | sdkmanager "build-tools;28.0.3"
- yes | sdkmanager "platforms;android-28"
jobs:
  include:
  - stage: check
    name: lint
    script: "./gradlew clean lint"
  - stage: check
    name: ktlint
    script: "./gradlew clean ktlint"
